name: CI
on:
  pull_request:
    branches:
      - main
#    paths-ignore:
#      - "../player-mobile-bcvideo"


jobs:
  flutter_test:
    name: Run flutter analyze and test
    runs-on: ubuntu-latest
#    env:
#      player_mobile_bcvideo: ../player-mobile-bcvideo/
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "8.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.6'
      - run: flutter pub get
#        working-directory: ${{env.player_mobile_bcvideo}}
#        - igno
#      - run: flutter analyze
#      - run: flutter test
#      - run: flutter build apk --debug