name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter analyze and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "8.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.6'
      - run: sh ./scripts/flutter_pub_get.sh
#      - run: flutter pub get
#      - run: flutter analyze
#      - run: flutter test
#      - run: flutter build apk --debug
